//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyStock.ScheduleServices.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPriceDay
    {
        public string TraDate { get; set; }
        public string StockNum { get; set; }
        public Nullable<long> M { get; set; }
        public Nullable<double> O { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> C { get; set; }
    }
}
